name: doomscroll_blocker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/logo.png"
  min_sdk_android: 24
  adaptive_icon_background: "#0c111e" # Darkest navy/charcoal
  adaptive_icon_foreground: "assets/logo.png"
